spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${APP_DB_URL:jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${APP_DB_USERNAME:ecommerceapp}
spring.datasource.password=${APP_DB_PASSWORD:ecommerceapp}
spring.jpa.hibernate.ddl-auto=none

spring.data.rest.base-path=/api

# allow jackson parser to process comments in payload
spring.jackson.parser.allow-comments=true
# application logging level
logging.level.org.springframework=INFO
